const mockData = [
    { id: 1, label: "Learn React Basics", isChecked: false, type: "active" },
    { id: 2, label: "Study JSX Syntax", isChecked: false, type: "active" },
    { id: 3, label: "Build First Component", isChecked: false, type: "active" },
    { id: 4, label: "Use State Hook", isChecked: false, type: "active" },
    { id: 5, label: "Understand Props", isChecked: false, type: "active" },
    { id: 6, label: "React Events", isChecked: false, type: "active" },
    { id: 7, label: "Conditional Rendering", isChecked: false, type: "active" },
    { id: 8, label: "List and Keys", isChecked: false, type: "active" },
    { id: 9, label: "React Fragments", isChecked: false, type: "active" },
    { id: 10, label: "Forms in React", isChecked: false, type: "active" },
    { id: 11, label: "Lift State Up", isChecked: false, type: "active" },
    { id: 12, label: "Lifting State Practice", isChecked: false, type: "active" },
    { id: 13, label: "React useEffect", isChecked: false, type: "active" },
    { id: 14, label: "API Fetching", isChecked: false, type: "active" },
    { id: 15, label: "Custom Hooks", isChecked: false, type: "active" },
    { id: 16, label: "React Router Intro", isChecked: false, type: "active" },
    { id: 17, label: "Nested Routes", isChecked: false, type: "active" },
    { id: 18, label: "React Context API", isChecked: false, type: "active" },
    { id: 19, label: "Theme Toggle App", isChecked: false, type: "active" },
    { id: 20, label: "Dark Mode Feature", isChecked: false, type: "active" },
    { id: 21, label: "useRef Usage", isChecked: false, type: "active" },
    { id: 22, label: "Imperative Handle", isChecked: false, type: "active" },
    { id: 23, label: "Forward Refs", isChecked: false, type: "active" },
    { id: 24, label: "React.memo()", isChecked: false, type: "active" },
    { id: 25, label: "Performance Optimization", isChecked: false, type: "active" },
    { id: 26, label: "Code Splitting", isChecked: false, type: "active" },
    { id: 27, label: "Error Boundaries", isChecked: false, type: "active" },
    { id: 28, label: "React Suspense", isChecked: false, type: "active" },
    { id: 29, label: "Lazy Loading", isChecked: false, type: "active" },
    { id: 30, label: "React DevTools", isChecked: false, type: "active" },
    { id: 31, label: "Testing Components", isChecked: false, type: "active" },
    { id: 32, label: "Jest Basics", isChecked: false, type: "active" },
    { id: 33, label: "React Testing Library", isChecked: false, type: "active" },
    { id: 34, label: "Snapshot Testing", isChecked: false, type: "active" },
    { id: 35, label: "React Query Intro", isChecked: false, type: "active" },
    { id: 36, label: "TanStack Query", isChecked: false, type: "active" },
    { id: 37, label: "Pagination Setup", isChecked: false, type: "active" },
    { id: 38, label: "Infinite Scroll", isChecked: false, type: "active" },
    { id: 39, label: "Authentication Flow", isChecked: false, type: "active" },
    { id: 40, label: "JWT Handling", isChecked: false, type: "active" },
    { id: 41, label: "Protected Routes", isChecked: false, type: "active" },
    { id: 42, label: "Firebase Auth", isChecked: false, type: "active" },
    { id: 43, label: "Form Validation", isChecked: false, type: "active" },
    { id: 44, label: "Zod Integration", isChecked: false, type: "active" },
    { id: 45, label: "Formik or RHF", isChecked: false, type: "active" },
    { id: 46, label: "UI Libraries Intro", isChecked: false, type: "active" },
    { id: 47, label: "Tailwind CSS", isChecked: false, type: "active" },
    { id: 48, label: "Styled Components", isChecked: false, type: "active" },
    { id: 49, label: "Component Reusability", isChecked: false, type: "active" },
    { id: 50, label: "Final React Project", isChecked: false, type: "active" },
];

export default mockData;
