const mockData = [
    {
        id: 1,
        label: "Learn React 1",
        isChecked: false,
        type: "active",
    },
    {
        id: 2,
        label: "Learn React 2",
        isChecked: false,
        type: "active",
    },
    {
        id: 3,
        label: "Learn React 3",
        isChecked: false,
        type: "active",
    },
    {
        id: 4,
        label: "Learn React 4",
        isChecked: false,
        type: "active",
    },
    {
        id: 5,
        label: "Learn React 5",
        isChecked: false,
        type: "active",
    },
    {
        id: 6,
        label: "Learn React 6",
        isChecked: false,
        type: "active",
    },
    {
        id: 7,
        label: "Learn React 7",
        isChecked: false,
        type: "active",
    },
    {
        id: 8,
        label: "Learn React 8",
        isChecked: false,
        type: "active",
    },
    {
        id: 9,
        label: "Learn React 9",
        isChecked: false,
        type: "active",
    },
    {
        id: 10,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 11,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 12,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 13,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 14,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 15,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 16,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 17,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 18,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 19,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 20,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 21,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 22,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
    {
        id: 23,
        label: "Learn React 10",
        isChecked: false,
        type: "active",
    },
];

export default mockData;
